// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DonateDialog: typeof import('./src/components/DonateDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    FooterArea: typeof import('./src/components/FooterArea.vue')['default']
    FormArea: typeof import('./src/components/FormArea.vue')['default']
    LaminateResult: typeof import('./src/components/result-area/LaminateResult.vue')['default']
    LayerAttributeInput: typeof import('./src/components/LayerAttributeInput.vue')['default']
    LayerResult: typeof import('./src/components/result-area/LayerResult.vue')['default']
    LoadingMask: typeof import('./src/components/LoadingMask.vue')['default']
    NDivider: typeof import('naive-ui')['NDivider']
    NDynamicInput: typeof import('naive-ui')['NDynamicInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NProgress: typeof import('naive-ui')['NProgress']
    ResultArea: typeof import('./src/components/result-area/ResultArea.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}

export {}
