// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CopyrightFooter: typeof import('./src/components/CopyrightFooter.vue')['default']
    FormArea: typeof import('./src/components/FormArea.vue')['default']
    LaminateDiagram: typeof import('./src/components/LaminateDiagram.vue')['default']
    LaminateResult: typeof import('./src/components/result-area/LaminateResult.vue')['default']
    LayerAttributeInput: typeof import('./src/components/LayerAttributeInput.vue')['default']
    LayerResult: typeof import('./src/components/result-area/LayerResult.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDivider: typeof import('naive-ui')['NDivider']
    NDynamicInput: typeof import('naive-ui')['NDynamicInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NProgress: typeof import('naive-ui')['NProgress']
    ResultArea: typeof import('./src/components/result-area/ResultArea.vue')['default']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}

export {}
